name: Build DEV
run-name: ${{ github.actor }} is testing out Build Stuff DEV
on:
  workflow_dispatch:
  push:
    branches: [dev]

jobs:
  Runs-On-Dev:
    runs-on: ubuntu-latest

    environment:
      name: DEV

    outputs:
      variable_from_step: ${{ steps.test_output.outputs.HELLO }}

    steps:
      - name: Echos the repo variables
        run: echo "Hallo ${{ vars.FOO }}."

      - name: Define something
        id: test_output
        run: HELLO=$(echo ${{ vars.HELLO }})

  Also-Runs-On-De:
    runs-on: ubuntu-latest
    needs: Runs-On-Dev
    steps:
      - name: Output somethin
        env:
          VARIABLE_FROM_STEP: ${{needs.Runs-On-Dev.outputs.variable_from_step}}
        run: echo $VARIABLE_FROM_STEP
