name: Build PROD
run-name: ${{ github.actor }} is testing out Build Stuff PROD
on:
  workflow_dispatch:
  push:
    branches: [main, feature]

jobs:
  Runs-On-PROD:
    runs-on: ubuntu-latest

    environment:
      name: PROD

    steps:
      - name: Check unicorn affected
        id: unicorn-affected
        env:
          HeadRef: ${{ github.head_ref }} #The target branch e.g. main (feature/unicorn-app)
          RefName: ${{ github.ref_name }} #The branch being merged e.g. (unicorn-pipe-rel2)
        run: |
          echo '{"targetBranch": "${{env.HeadRef}}", "sourceBranch": "${{env.Refname}}" }'
      - name: Echos the env variables
        run: echo "Hallo ${{ vars.HELLO }}."
      - name: Echos the repo variables
        run: echo "Hallo ${{ vars.FOO }}."

      - name: checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: yarn install
        run: yarn install

      - name: Check unicorn affected
        run: |
          UNICORN=$(yarn --silent debug)
          if [ "$UNICORN" = 'true' ]; then
              echo "unicorn is detected"
          else
              echo "No unicorn"
          fi

      - name: Check unicorn affected (debug)
        run: |
          UNICORN=$(yarn --silent is-unicorn)
          if [ "$UNICORN" = 'true' ]; then
              echo "unicorn is detected"
          else
              echo "No unicorn"
          fi



