name: Build PROD
run-name: ${{ github.actor }} is testing out Build Stuff PROD
on:
  workflow_dispatch:
  push:
    branches: [main, feature]

jobs:
  Runs-On-PROD:
    runs-on: ubuntu-latest

    environment:
      name: PROD

    steps:
      - name: Echos the env variables
        run: echo "Hallo ${{ vars.HELLO }}."
      - name: Echos the repo variables
        run: echo "Hallo ${{ vars.FOO }}."

      - name: checkout main
        uses: actions/checkout@v4
        with:
          ref: main

      - name: checkout
        uses: actions/checkout@v4

      - name: yarn install
        run: yarn install

      - name: Check unicorn affected
        run: |
          git branch -a
          yarn nx show projects --branch origin/main --affected



