name: Build PROD
run-name: ${{ github.actor }} is testing out Build Stuff PROD
on:
  # workflow_dispatch:
  # push:
  #   branches: [main, feature]
  workflow_dispatch:
  create:
  pull_request:
    types:
      - opened
      - synchronize
      - labeled
jobs:
  Runs-On-PROD:
    runs-on: ubuntu-latest
    env:
      ARTIFACT_NAME: ActionsTest-${{ github.sha }}
    environment:
      name: PROD
    outputs:
      artifact-url: ${{ steps.artifact-upload-step.outputs.artifact-url }}
      artifact-name: ${{ env.ARTIFACT_NAME }}
    steps:
      - name: Echos the env variables
        run: echo "Hallo ${{ vars.HELLO }}."
      - name: Echos the repo variables
        run: echo "Hallo ${{ vars.FOO }}."

      - name: checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: 'Upload Artifact'
        uses: actions/upload-artifact@v4
        id: artifact-upload-step
        env:
          GIT_COMMIT_SHA: ${{ github.sha }}
        with:
          name: ${{ env.ARTIFACT_NAME }}
          overwrite: true
          path: .
          retention-days: 1
      - name: Set env variables
        run: |
          echo artifact-url=${{ steps.artifact-upload-step.outputs.artifact-url }} >> $GITHUB_ENV

  Get-Artifact-PROD:
    runs-on: ubuntu-latest
    needs: Runs-On-PROD
    steps:
        - uses: actions/download-artifact@v4
          with:
            name: ${{ needs.Runs-On-PROD.outputs.artifact-name }}
        - name: Display structure of downloaded files
          run: ls -R

      # - name: yarn install
      #   run: yarn install

      # - name: Check unicorn affected
      #   run: |
      #     UNICORN=$(yarn --silent debug)
      #     if [ "$UNICORN" = 'true' ]; then
      #         echo "unicorn is detected"
      #     else
      #         echo "No unicorn"
      #     fi

      # - name: Check unicorn affected (debug)
      #   run: |
      #     UNICORN=$(yarn --silent is-unicorn)
      #     if [ "$UNICORN" = 'true' ]; then
      #         echo "unicorn is detected"
      #     else
      #         echo "No unicorn"
      #     fi



