name: Build PROD
run-name: ${{ github.actor }} is testing out Build Stuff PROD
on:
  # workflow_dispatch:
  # push:
  #   branches: [main, feature]
  workflow_dispatch:
  create:
  pull_request:
    types:
      - opened
      - synchronize
      - labeled
jobs:
  Runs-On-PROD:
    runs-on: ubuntu-latest

    environment:
      name: PROD

    steps:
      - name: Echos the env variables
        run: echo "Hallo ${{ vars.HELLO }}."
      - name: Echos the repo variables
        run: echo "Hallo ${{ vars.FOO }}."

      - name: checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      # - name: test
      #   env:
      #     GIT_COMMIT_SHA: ${{ github.sha }}
      #   run: |
      #     ls -al
      #     echo $GIT_COMMIT_SHA

      - name: 'Upload Artifact'
        uses: actions/upload-artifact@v4
        id: artifact-upload-step
        env:
          GIT_COMMIT_SHA: ${{ github.sha }}
        with:
          name: ActionsTest-$GIT_COMMIT_SHA
          overwrite: true
          path: .
          retention-days: 1

      - name: Output artifact ID
        run:  echo 'Artifact ID is ${{ steps.artifact-upload-step.outputs.artifact-id }}'

      # - name: yarn install
      #   run: yarn install

      # - name: Check unicorn affected
      #   run: |
      #     UNICORN=$(yarn --silent debug)
      #     if [ "$UNICORN" = 'true' ]; then
      #         echo "unicorn is detected"
      #     else
      #         echo "No unicorn"
      #     fi

      # - name: Check unicorn affected (debug)
      #   run: |
      #     UNICORN=$(yarn --silent is-unicorn)
      #     if [ "$UNICORN" = 'true' ]; then
      #         echo "unicorn is detected"
      #     else
      #         echo "No unicorn"
      #     fi



